site_name: BC ELN-BCHDP Support Service
site_url: https://bceln.github.io/bchdp-docs
repo_url: https://github.com/bceln/bchdp-docs
edit_uri: edit/main/docs


theme:
  name: material
  custom_dir: overrides
  logo: 'assets/BC_ELN_2014logo_rev_whitegold.png'
  palette:
    primary: custom
    accent: 'indigo'
  language: 'en'
  features:
    - content.action.edit
    - content.action.view
    - announce.dismiss
  icon:
    admonition:
      bchdp: octicons/sync-24
    edit: material/pencil
    view: material/eye

markdown_extensions:
  - admonition
  - footnotes
  - toc:
        permalink: True
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.critic
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Grant Application Support:
    - Service Information: support/support.md
    - Arca Hosting: support/arcahosting.md
    - General Resources: support/generalresources.md
    - Resources by Application Section: support/applicationsection.md
  - About:
    - About: about/about.md
    - Contact: about/contact.md
