site_name: BC ELN-BCHDP Support Documentation
site_url: https://bceln.github.io/bchdp-docs
repo_url: https://github.com/bceln/bchdp-docs
edit_uri: edit/main/docs


theme:
  name: material
  logo: 'assets/bceln_logo.jpg'
  palette:
    primary: 'blue'
    accent: 'light blue'
  language: 'en'
  features:
    - content.action.edit
    - content.action.view
    - announce.dismiss
  icon:
    edit: material/pencil
    view: material/eye

markdown_extensions:
  - admonition
  - footnotes
  - toc:
        permalink: True
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - About:
    - About: about/about.md
    - Contact: about/contact.md
